version: '3'
services:
  jupyter:
    user: root
    volumes:
      - "./notebooks:/home/joyvan/work"
    environment:
      GRANT_SUDO: 'yes'

    ports:
      - "8888:8888"
    build: jupyter

  mlflow:
    environment:
      DB_HOST: host.docker.internal
      DB_USER: splice
      DB_PASSWORD: [DB PASSWORD]
      FRAMEWORK_NAME: amrit-streamtest-6160590510
      MODE: development
      ENVIRONMENT: aws
    ports:
      - "5001:5001"
      - "5003:5003"

    build:
      args:
        splice_base_image_version: 0.0.4
        splice_base_artifact_uri: https://s3.amazonaws.com/splicemachine/artifacts
        github_PAT: [YOUR GITHUB PERSONAL ACCESS TOKEN]

      context: mlflow

  bobby:
    privileged: true
    environment:
      DB_HOST: host.docker.internal
      DB_USER: splice
      DB_PASSWORD: [REPLACE WITH DB PASSWORD]
      FRAMEWORK_NAME: amrit-streamtest
      MLFLOW_URL: "http://mlflow:5001"
      AZURE_USERNAME: [REPLACE WITH AZURE USERNAME]
      AZURE_PASSWORD: [REPLACE WITH AZURE PASSWORD]
      AWS_ACCESS_KEY_ID: [REPLACE WITH AWS ACCESS KEY]
      AWS_SECRET_ACCESS_KEY: [REPLACE WITH AWS SECRET KEY]
      SAGEMAKER_ROLE: arn:aws:iam::[AWS ACCOUNT NUMBER]:role/splice-sagemaker
      MODE: development
      ENVIRONMENT: aws
    build:
      args:
        splice_base_image_version: 0.0.4
        splice_base_artifact_uri: https://s3.amazonaws.com/splicemachine/artifacts
        github_PAT: [YOUR GITHUB PERSONAL ACCESS TOKEN]
      context: bobby


