version: '3'
services:
  jupyter:
    user: root
    volumes:
      - "./notebooks:/home/joyvan/work"
    environment:
      GRANT_SUDO: 'yes'

    ports:
      - "8888:8888"
    build:
      args:
        splice_base_image_version: 0.0.2
      context: jupyter
    image: ml-workflow_jupyter:0.0.15

  mlflow:
    environment:
      FRAMEWORK_NAME: streamtest-6160590510
      MODE: production
      ENVIRONMENT: aws
      TASK_NAME: dev
      COMPONENT: mlmanager
    image: splicemachine/sm_k8_mlflow:0.1.23
    ports:
      - "5001:5001"
      - "5003:5003"
    build:
      args:
        splice_base_image_version: 0.0.2
      context: ./
      dockerfile: ./mlflow/Dockerfile
    env_file:
      - local.env

  bobby:
    privileged: true
    environment:
      FRAMEWORK_NAME: streamtest
      MLFLOW_URL: "http://mlflow:5001"
      MODE: production
      ENVIRONMENT: aws
    image: splicemachine/sm_k8_bobby:0.1.23
    build:
      args:
        splice_base_image_version: 0.0.2
      context: ./
      dockerfile: ./bobby/Dockerfile
    env_file:
      - local.env

