version: '3'
services:
  jupyter:
    user: root
    volumes:
      - "./notebooks:/home/joyvan/work"
    environment:
      AWS_ACCESS_KEY_ID: AKIAILC2A7RT2GK5RFBQ
      AWS_SECRET_ACCESS_KEY: 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
      GRANT_SUDO: 'yes'

    ports:
      - "8888:8888"
    build: jupyter

  mlflow:
    environment:
      DB_HOST: host.docker.internal
      DB_USER: splice
      DB_PASSWORD: admin
      FRAMEWORK_NAME: amrit-streamtest-6160590510
      ENVIRONMENT: aws
      S3_BUCKET_NAME: s3://splice-demo/machine-learning/sync
      AWS_ACCESS_KEY_ID: AKIAILC2A7RT2GK5RFBQ
      AWS_SECRET_ACCESS_KEY: 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
      MODE: development
    ports:
      - "5001:5001"
      - "5003:5003"

    build:
      args:
        splice_base_image_version: 0.0.4
        splice_base_artifact_uri: https://s3.amazonaws.com/splicemachine/artifacts
        github_PAT: 673b31154d0c179f921dd03d1e74f4fe9f58c337
      context: mlflow
    
  bobby:
    privileged: true
    environment:
      DB_HOST: host.docker.internal
      DB_USER: splice
      DB_PASSWORD: admin
      FRAMEWORK_NAME: amrit-streamtest-6160590510
      ENVIRONMENT: aws
      MLFLOW_URL: "http://mlflow:5001"
      AWS_ACCESS_KEY_ID: AKIAILC2A7RT2GK5RFBQ
      AWS_SECRET_ACCESS_KEY: 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
      SAGEMAKER_ROLE: arn:aws:iam::953558963498:role/splice-sagemaker
      MODE: development
    build:
      args:
        splice_base_image_version: 0.0.4
        splice_base_artifact_uri: https://s3.amazonaws.com/splicemachine/artifacts
        github_PAT: 673b31154d0c179f921dd03d1e74f4fe9f58c337
      context: bobby


