version: "3"
services:
  jupyter:
    user: root
    volumes:
      - "./notebooks:/home/joyvan/work"
    environment:
      GRANT_SUDO: "yes"
    ports:
      - "8888:8888"
    build:
      args:
        splice_base_image_version: 0.0.2
      context: jupyter
    image: splicemachine/ml-workflow_jupyter:0.0.3
  mlflow:
    environment:
      DB_HOST: host.docker.internal
      DB_USER: mlmanager
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      FRAMEWORK_NAME: my-framework
      MODE: development
      ENVIRONMENT: ${ENVIRONMENT:-default}
      JUP_AUTH0_CERT: "-----BEGIN CERTIFICATE----- MIIDETCCAfmgAwIBAgIJZiptKnrWcmahMA0GCSqGSIb3DQEBCwUAMCYxJDAiBgNV BAMTG3NwbGljZW1hY2hpbmUtZGV2LmF1dGgwLmNvbTAeFw0xNzA2MDcwMjQ1MjVa Fw0zMTAyMTQwMjQ1MjVaMCYxJDAiBgNVBAMTG3NwbGljZW1hY2hpbmUtZGV2LmF1 dGgwLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANx8LzWqriPH hX7Odo/eoyYEun2JxIPCIWB/m2Olu/kcWIOGOSy7ckV8B3bWzT73wQaL7e2ep74w AsoNq4IS0K+hsNjdUCCwPegoZQLrA7p6gRXiRcXVLIAalwq/ezul8DQgb0hwucf2 U3GX6JAIAdX9midTbP9qm0T8/y618GCuA3LG5yAMBR1kIRAc6KDr1EqOH2yirl5p CcwFQRupg0G8cH1aLQ8CJfNawsRBFBSBLGG9FWiQbrTBsPdQ+6FO1H6VNWRF9N+4 9/BMVQRbRaNvnCNZ6MrraiPviD0PMNhZ24ZNw9XOKhcH5QjqsohQOg3IZxEuwRC9 Ub2Cu+4L8kUCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU4/IP 3R/ieUzDbtKHUGjjHaiL/QAwDgYDVR0PAQH/BAQDAgKEMA0GCSqGSIb3DQEBCwUA A4IBAQAsDIlP/Bm+jEUa7IZQhtG3Vw4l2A72eUH0vEcNXPYkMMBdggCEBd4c17pg CtbYZk1Sn3Vj5h5uhhtFpwN3xt2dgRelPmlnyTcH5h8/VOEafZyBWC5uVp0SIs28 6k/ASjyPlRi+xJEZ2zJCsaPkLlIOhIvSFW0OFzU2ogSD5dxvG6/iwqDaYirNitSL Yt/bOdOPdFyklfu7eXA9haJM5aUUuY//Rv46x/E3FjBM9c5Q8afVISHDdrjSc4T+ d3QijQoOqAGQ4HGJEk/SH3QuWcwxvk4sr40TNY4EC9INi9bRc05E2+F+Q8Llpv91 MhOwJ404BzrcCV98cFaeax8sR1MY -----END CERTIFICATE-----"
    image: splicemachine/sm_k8_mlflow:0.1.29
    ports:
      - "5001:5001"
      - "5003:5003"
    build:
      args:
        splice_base_image_version: 0.0.2
      context: ./
      dockerfile: ./mlflow/Dockerfile
  bobby:
    privileged: true
    environment:
      DB_HOST: host.docker.internal
      DB_USER: mlmanager
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      FRAMEWORK_NAME: my-framework
      MLFLOW_URL: "http://mlflow:5001"
      CREATOR_ROLE: "true"
      AZURE_USERNAME: ${AZURE_USERNAME}
      AZURE_PASSWORD: ${AZURE_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SAGEMAKER_ROLE: ${SAGEMAKER_ROLE}
      MODE: production
      ENVIRONMENT: ${ENVIRONMENT:-default}
    image: splicemachine/sm_k8_bobby:0.1.29
    build:
      args:
        server_image_tag: 0.0.15
        splice_base_image_version: 0.0.2
      context: ./
      dockerfile: ./bobby/Dockerfile
  feature_store:
    environment:
      DB_HOST: host.docker.internal
      DB_USER: mlmanager
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      FRAMEWORK_NAME: my-framework
      MODE: development
      ROOT_PATH: / # Change this to /featurestore in the cloud
      ENVIRONMENT: ${ENVIRONMENT:-default}
      AIRFLOW_URL: "http://host.docker.internal:8081/api/v1"
      AIRFLOW_USER: airflow
      AIRFLOW_PASSWORD: airflow
      JUP_AUTH0_CERT: "-----BEGIN CERTIFICATE----- MIIDETCCAfmgAwIBAgIJZiptKnrWcmahMA0GCSqGSIb3DQEBCwUAMCYxJDAiBgNV BAMTG3NwbGljZW1hY2hpbmUtZGV2LmF1dGgwLmNvbTAeFw0xNzA2MDcwMjQ1MjVa Fw0zMTAyMTQwMjQ1MjVaMCYxJDAiBgNVBAMTG3NwbGljZW1hY2hpbmUtZGV2LmF1 dGgwLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANx8LzWqriPH hX7Odo/eoyYEun2JxIPCIWB/m2Olu/kcWIOGOSy7ckV8B3bWzT73wQaL7e2ep74w AsoNq4IS0K+hsNjdUCCwPegoZQLrA7p6gRXiRcXVLIAalwq/ezul8DQgb0hwucf2 U3GX6JAIAdX9midTbP9qm0T8/y618GCuA3LG5yAMBR1kIRAc6KDr1EqOH2yirl5p CcwFQRupg0G8cH1aLQ8CJfNawsRBFBSBLGG9FWiQbrTBsPdQ+6FO1H6VNWRF9N+4 9/BMVQRbRaNvnCNZ6MrraiPviD0PMNhZ24ZNw9XOKhcH5QjqsohQOg3IZxEuwRC9 Ub2Cu+4L8kUCAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU4/IP 3R/ieUzDbtKHUGjjHaiL/QAwDgYDVR0PAQH/BAQDAgKEMA0GCSqGSIb3DQEBCwUA A4IBAQAsDIlP/Bm+jEUa7IZQhtG3Vw4l2A72eUH0vEcNXPYkMMBdggCEBd4c17pg CtbYZk1Sn3Vj5h5uhhtFpwN3xt2dgRelPmlnyTcH5h8/VOEafZyBWC5uVp0SIs28 6k/ASjyPlRi+xJEZ2zJCsaPkLlIOhIvSFW0OFzU2ogSD5dxvG6/iwqDaYirNitSL Yt/bOdOPdFyklfu7eXA9haJM5aUUuY//Rv46x/E3FjBM9c5Q8afVISHDdrjSc4T+ d3QijQoOqAGQ4HGJEk/SH3QuWcwxvk4sr40TNY4EC9INi9bRc05E2+F+Q8Llpv91 MhOwJ404BzrcCV98cFaeax8sR1MY -----END CERTIFICATE-----"
    ports:
      - "8000:8000"
    build:
      args:
        splice_base_image_version: 0.0.2
      context: ./
      dockerfile: ./feature_store/Dockerfile
