apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "retraining.identifier" . }}
  namespace: {{ .Values.entity.namespace }}
  labels:
    identifier: {{ template "retraining.identifier" . }}
{{ include "retraining.ownerRef" . | indent 2}}
spec:
  selector:
    matchLabels:
      identifier: {{ template "retraining.identifier" . }}
  schedule: "{{ .Values.entity.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ template "retraining.identifier" . }}-serviceaccount
          volumes:
            - name: {{ template "retraining.identifier" . }}-ephem-vol
              emptyDir: {}
          initContainers:
            - name: {{ template "retraining.identifier" . }}-loader
              env:
{{ include "retraining.dbEnvs" . | indent 16}}
                - name: JOB_NAME
                  value: {{ .Values.entity.name }}
                - name: RUN_ID
                  value: {{ .Values.entity.entityId }}
                - name: CONDA_ENV_NAME
                  value: {{ .Values.entity.condaEnv }}
                - name: MLFLOW_URL
                  value: {{ .Values.k8s.mlflowUrl }}
                - name: RETRAINING
                  value: {{ .Values.entity.retraining }}
              image: splicemachine/sm_k8_model-init:{{ .Values.versions.retriever }}
          containers:
          - name: {{ template "retraining.identifier" . }}
            image: splicemachine/sm_k8_model_retraining:{{ .Values.versions.retrainer }}
            env:
              - name: CONDA_ENV_NAME
                value: {{ .Values.entity.condaEnv }}
              - name: MOUNT_PATH
                value: /opt/ml/model
              - name: BEAKERX_SQL_DEFAULT_JDBC
                value: {{ .Values.db.jdbUrl }}
              - name: SPLICE_JUPYTER_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ template "retraining.identifier" . }}-db-secret
                    key: DB_USER
              - name: SPLICE_JUPYTER_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ template "retraining.identifier" . }}-db-secret
                    key: DB_PASSWORD
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
