apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "retraining.identifier" . }}-serviceaccount
  namespace: {{ .Values.k8s.namespace }}
  labels:
    identifier: {{ template "retraining.identifier" . }}
{{ include "retraining.ownerRef" . | indent 2}}