apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kdeploy.identifier" . }}-db-secret
  namespace: {{ .Values.model.namespace}}
{{ include "kdeploy.ownerRef" . | indent 4}}
type: Opaque
data:
  DB_USER: {{ .Values.db.user }}
  DB_PASSWORD: {{ .Values.db.password }}
  DB_HOST: {{ .Values.db.host }}
