apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdeploy.identifier" . }}
  namespace: {{ .Values.model.namespace }}
  labels:
    identifier: {{ template "kdeploy.identifier" . }}
{{ include "kdeploy.ownerRef" . | indent 2}}
spec:
  clusterIP: None
  selector:
    identifier: {{ template "kdeploy.identifier" . }}
  ports:
    - port: {{ .Values.serving.exposePort }}
      name: {{ .Values.model.runId }}
