apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kdeploy.identifier" . }}
  namespace: {{ .Values.k8s.namespace }}
  labels:
    identifier: {{ template "kdeploy.identifier" . }}
{{ include "kdeploy.ownerRef" . | indent 2}}