apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kdeploy.identifier" . }}
  namespace: {{ .Values.model.namespace }}
  labels:
    identifier: {{ template "kdeploy.identifier" . }}
  {{ include "kdeploy.ownerRef" . }}