apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kdeploy.identifier" . }}-db-secret
  namespace: {{ .Values.k8s.namespace}}
{{ include "kdeploy.ownerRef" . | indent 2 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.user }}
  DB_PASSWORD: {{ .Values.db.password }}
  DB_HOST: {{ .Values.db.host }}
